# Generated by Django 4.2.21 on 2025-05-31 20:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_timesheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_period_start', models.DateField(default=datetime.date.today)),
                ('pay_period_end', models.DateField(default=datetime.date.today)),
                ('date', models.DateField()),
                ('earn_code', models.CharField(choices=[('Regular Pay', 'Regular Pay'), ('Overtime', 'Overtime')], default='Regular Pay', max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('submitted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Timesheet',
        ),
    ]
