# Generated by Django 4.2.21 on 2025-05-31 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_timesheets_delete_timesheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheets',
            name='pay_period_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='timesheets',
            name='pay_period_start',
            field=models.DateField(),
        ),
    ]
